//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursachproj
{
    using System;
    using System.Collections.Generic;
    
    public partial class rez
    {
        public int id { get; set; }
        public string fullname { get; set; }
        public string yearOfBirth { get; set; }
        public string education { get; set; }
        public string experience { get; set; }
        public string post { get; set; }
        public string citizenship { get; set; }
        public string typeofemployment { get; set; }
        public byte[] photo { get; set; }
    }
}
